#ifndef DEFINES_H
#define DEFINES_H

#define GAME_TITLE "Ninja Fighter"

//GLOBAL SETTINGS
#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 380

#define TOP_HEIGHT 100
#define BOTTOM_HEIGHT 75
#define BACKGROUND_HEIGHT SCREEN_HEIGHT
#define BACKGROUND_WIDTH 1600

#define TIME_BTW_ANIMATIONS 100
#define TIME_BTW_ENEMIES 500

#define ENEMIES_LVL1 10

#define PLAYER_SPEED 2

//SPRITE RELATED
#define SPRITE_WIDTH 45
#define SPRITE_HEIGHT 100

#define DEFAULT_SPRITE_POSITION_X ( SCREEN_WIDTH / 2 ) - SPRITE_WIDTH
#define DEFAULT_SPRITE_POSITION_Y SCREEN_HEIGHT - SPRITE_HEIGHT - BOTTOM_HEIGHT
#define DEFAULT_SPRITE_HEIGHT 100
#define DEFAULT_SPRITE_WIDTH 45

#define DEFAULT_ENEMY_POSITION_X - (DEFAULT_SPRITE_POSITION_X - 200)
#define DEFAULT_ENEMY_POSITION_Y DEFAULT_SPRITE_POSITION_Y

//LIMITS AND DEFAULT POSITION OF SOURCES RECT FOR THE SPRITES AND IMAGES
#define SOURCE_POS_PLAYER_KNELT_LEFT_X 160
#define SOURCE_POS_PLAYER_KNELT_RIGHT_X 0
#define SOURCE_POS_PLAYER_KNELT_Y (SPRITE_HEIGHT * 2 + 10)

#define SOURCE_POS_PLAYER_STANDING_RIGHT_X 0
#define SOURCE_POS_PLAYER_STANDING_RIGHT_Y 0
#define SOURCE_POS_PLAYER_STANDING_RIGHT_ACC (SPRITE_WIDTH + 2)
#define SOURCE_POS_PLAYER_STANDING_RIGHT_LIMIT_X (SPRITE_WIDTH * 4 + 2)
#define SOURCE_POS_BG_RIGHT_LIMIT_X BACKGROUND_WIDTH - SCREEN_WIDTH
#define RECT_POS_PLAYER_RIGHT_LIMIT_X SCREEN_WIDTH - SPRITE_WIDTH

#define SOURCE_POS_PLAYER_STANDING_LEFT_X (3 * SPRITE_WIDTH + 10)
#define SOURCE_POS_PLAYER_STANDING_LEFT_Y (SPRITE_HEIGHT + 7)
#define SOURCE_POS_PLAYER_STANDING_LEFT_ACC  - SPRITE_WIDTH
#define SOURCE_POS_PLAYER_STANDING_LEFT_LIMIT_X 0
#define SOURCE_POS_BG_LEFT_LIMIT_X 0
#define RECT_POS_PLAYER_LEFT_LIMIT_X 0

#define SOURCE_POS_PLAYER_JUMP_RIGHT_X 0
#define SOURCE_POS_PLAYER_JUMP_RIGHT_Y 325
#define SOURCE_POS_PLAYER_JUMP_RIGHT_X_ACC SPRITE_WIDTH
#define SOURCE_POS_PLAYER_JUMP_RIGHT_X_LIMIT 187

#define SOURCE_POS_PLAYER_JUMP_LEFT_X 250
#define SOURCE_POS_PLAYER_JUMP_LEFT_Y 426
#define SOURCE_POS_PLAYER_JUMP_LEFT_X_ACC - SPRITE_WIDTH
#define SOURCE_POS_PLAYER_JUMP_LEFT_LIMIT_X 70


#define SOURCE_POS_PLAYER_KICK_RIGHT_X 1
#define SOURCE_POS_PLAYER_KICK_RIGHT_Y 525
#define SOURCE_POS_PLAYER_KICK_RIGHT_ACC 80
#define SOURCE_POS_PLAYER_KICK_RIGHT_LIMIT_X 285

#define SOURCE_POS_PLAYER_KICK_LEFT_X 318
#define SOURCE_POS_PLAYER_KICK_LEFT_Y 621
#define SOURCE_POS_PLAYER_KICK_LEFT_ACC - 80
#define SOURCE_POS_PLAYER_KICK_LEFT_LIMIT_X 80

#define JUMP_HEIGHT 25

//DEFAULTS STRUCTURES SETTINGS
#define DEFAULT_PLAYER_LIFEPOINTS 10
#define DEFAULT_PLAYER_HITDAMAGE 10
#define DEFAULT_GRABBING_ENEMY_LIFEPOINTS 10
#define DEFAULT_GRABBING_ENEMY_HITDAMAGE 1

#endif //DEFINES_H
